name: build

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Build Push
        #uses: docker/build-push-action@v2
        #with:
          #tags: hosts_contracts
      #- name: Docker Run
        #uses: addnab/docker-run-action@v3
        #with:
          #image: hosts_contracts
          #options: --name hosts_contracts_container
          #run: /hosts/entrypoint.sh
      #- name: Docker Copy
        #uses: tj-actions/docker-cp@v2
        #with:
          #container: hosts_contracts_container
          #source: hosts/build/hosts
          #destination: ./build/hosts
          
      - name: Docker
        run: |
          docker build --tag hosts:test .
          exec docker run -v "/var/run/docker.sock":"/var/run/docker.sock" --name hosts-test --entrypoint="/hosts/entrypoint.sh" hosts:test
          docker cp hosts-test:hosts/build/hosts ./build/hosts
        
      - name: Version
        id: get_version
        run: |
          echo "VER=$(curl -IkLs -o /tmp/NUL -w %{url_effective} https://github.com/StevenBlack/hosts/releases/latest | grep -o "[^/]*$")" >> $GITHUB_OUTPUT
      - name: Upload 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/hosts
          tag: ${{ steps.get_version.outputs.VER }}
          overwrite: true
          file_glob: true
          